# Generated by Django 4.1.7 on 2023-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('area_of_site', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Your_dream_building', models.CharField(choices=[('residential', 'Residential'), ('hospital', 'Hospital'), ('educational', 'Educational'), ('commercial', 'Commercial'), ('assembly', 'Assembly'), ('storage', 'Storage')], max_length=20)),
            ],
        ),
    ]
